### ISSUE TITLE
Can't sync to legato/branches/master.xml

### ISSUE THREAD

**Issue by dpfrey** [legatoproject/manifest#10]
```
$ repo sync -d
Fetching project legato-3rdParty-kconfig-frontends
Fetching project legato-PlatformAdaptor-DcsLinux
Fetching project legato-PlatformAdaptor-WdogLinux
Fetching project legato-Dualsys
Fetching project legato-PlatformAdaptor-QmiBin-wp85
error: Cannot fetch legato-3rdParty-kconfig-frontends (GitError: legato-3rdParty-kconfig-frontends update-ref: fatal: 2b368eb4335864c8bd5e38c100a001a180b1d466^0: not a valid SHA1
)
Fetching project legato-PlatformAdaptor-AT
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dfrey/sw/repo/subcmds/sync.py", line 270, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/dfrey/sw/repo/subcmds/sync.py", line 314, in _FetchHelper
    prune=opt.prune)
  File "/home/dfrey/sw/repo/project.py", line 1189, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/dfrey/sw/repo/project.py", line 2271, in _InitMRef
    self._InitAnyMRef(R_M + self.manifest.branch)
  File "/home/dfrey/sw/repo/project.py", line 2283, in _InitAnyMRef
    self.bare_git.UpdateRef(ref, dst, message=msg, detach=True)
  File "/home/dfrey/sw/repo/project.py", line 2573, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/dfrey/sw/repo/project.py", line 2650, in runner
    p.stderr))
GitError: legato-3rdParty-kconfig-frontends update-ref: fatal: 2b368eb4335864c8bd5e38c100a001a180b1d466^0: not a valid SHA1
```

The object does indeed not exist in the repository:
```
$ git show 2b368eb4335864c8bd5e38c100a001a180b1d466
fatal: bad object 2b368eb4335864c8bd5e38c100a001a180b1d466
```

Now if I add the upstream repository: `$ git remote add upstream git://ymorin.is-a-geek.org/kconfig-frontends && git fetch --all`

I get this:
```
$ git show 2b368eb4335864c8bd5e38c100a001a180b1d466
tag v4.11.0.1
Tagger: Yann E. MORIN <yann.morin.1998@free.fr>
Date:   Tue May 9 21:49:10 2017 +0200

Tagging vv4.11.0.1
-----BEGIN PGP SIGNATURE-----

iQI1BAABCAAfBQJZEh02GBx5YW5uLm1vcmluLjE5OThAZnJlZS5mcgAKCRC5nN6O
oVbQXftSEAC3UpgwsowF89lqiKTqeiNwk9eM5BJ5xZp7J8iHx8LRLUn+mXB0Hh+b
99EkNo16GgGgSrPs78ot0AmTiWaIj/Yjek96Ddh/Th+JgZK11J4oon2DE9hnSWua
h08fmVcszKaSgNsl5NmqxxPY2xQL7nS1yWanR+W9xS2tVp1dretqO/2pm9vbs3w7
V+WPVi8wyru6BIx9CqwM7GK1TBPGVWUKOb7Irww0N9zfqV54Hmi+2FL0Qw2JWcZY
8d4sLgWVjd/NDWBSkggpP6Eien74t5GGsz2tu94YYPE/nhO977JVzin7aRo9Vl2i
I+gCovWo3uT38m8kP/OXI/zW1nv5RC+TjdotfgXqEMYSkJdRkTu9wVdUW7nNJUhK
9jc1NL9ZotTpBjAo8pFPq27V07AxvSsA7zu4XRUMlD3al0WCRwJPhYdvI4YYefPJ
jUFEdFYqaBOF5gWQOrt1XcKyqq+Kc/l2/HMrIvUS8+aHzaykZu3HlZ1afg5DlTvo
Dfu5/1YUxrJwTqdJqXPSX2DPUoI7WC2/dTmzBzBggKPU9CQiqHkPpbYmxNItMe3f
lJE5f2WjqvLVtBApsB5lOLlgzpe6/2oAa7Xpz2z3a+EDUbi8uYeWM1/NTvXomji1
/oRNMiH3B5+ETwGIBuAMFLdPDJ9/Obcs47uYdEqXQz8NRdQ38YEOiw==
=NxMx
-----END PGP SIGNATURE-----

commit f22fce3a308be1c7790ebefc6bbedb33c5f7c86a
Author: Yann E. MORIN <yann.morin.1998@free.fr>
Date:   Tue May 9 21:48:51 2017 +0200

    version: bump packaging version

    Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>

diff --git a/.version b/.version
index 9846f0a..432d1dc 100644
--- a/.version
+++ b/.version
@@ -1,2 +1,2 @@
 4.11.0 a351e9b9fc24e982ec2f0e76379a49826036da12 Fearless Coyote
-0
+1
```

**Comment by CoRfr** [comment]
@dpfrey, should be fixed now, can you confirm?

**Comment by dpfrey** [comment]
Confirmed
